server:
  port: 8080

spring:
  application:
    name: dcp-task

  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql