server:
  port: 8080

spring:
  application:
    name: dcp-mailsearch

  profiles:
    active: dev

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql